name: Release Userscript

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build userscript
        run: bun run build:userscript
      
      - name: Upload userscript to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/spitroast.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
